### ISSUE TITLE
🔌  Plugin: Tekton, v2

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#113]
## Goal
Enhance the Janus UI plugin for Tekton Pipelines.  Incorporate the PLR log viewer from the OpenShift Console into the UI plugin.

## What problem does this solve
I'd like to see detailed logs of the tekton pipeline which associated with a service.

## Acceptance criteria
- I should be able to access the Task Run logs of the PLR.
- I should be able to click on the PLR viz, and be navigated directly to the Task Run log in context in the PLR log viewer.

## Additional context
![tekton-log-viewer](https://user-images.githubusercontent.com/12504403/218326265-3f5b2c98-6925-413e-b257-0044da060a09.gif)

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/329
- [x] https://github.com/janus-idp/backstage-plugins/issues/271
- [x] https://github.com/janus-idp/backstage-plugins/issues/285
- [x] https://github.com/janus-idp/backstage-plugins/issues/343
- [x] https://github.com/janus-idp/backstage-plugins/issues/406
- [x] https://github.com/janus-idp/backstage-plugins/issues/408
- [x] https://github.com/janus-idp/backstage-plugins/issues/489
- [x] https://github.com/janus-idp/backstage-plugins/issues/488
- [x] https://github.com/janus-idp/backstage-plugins/issues/550
- [x] https://github.com/janus-idp/backstage-plugins/issues/551

**Comment by invincibleJai** [comment]
@serenamarie125 / @christophe-f  have linked some story/spikes for tekton V2, will be adding more as we progress based on spikes

cc @debsmita1 @divyanshiGupta

**Comment by zppinho** [comment]
I'm looking forward to this amazing new feature!

**Comment by rtaniwa** [comment]
Even though this isn't a net new plugin, should we add a story for doc review in case there are updates required?

**Comment by invincibleJai** [comment]
yeah we should add for QE and docs. @debsmita1 pls do the needful.

**Comment by invincibleJai** [comment]
> Even though this isn't a net new plugin, should we add a story for doc review in case there are updates required?

yeah we should add for QE and docs. @debsmita1 pls do the needful.

**Comment by invincibleJai** [comment]
Closing it as all linked tasks are in closed
