### ISSUE TITLE
🔌 Plugin: OCI Registry (JFrog) 

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#117]
## Goal
This epic aims to develop a new Backstage plugin in the Janus repo. This plugin should allow Backstage users to view details of an image related to a catalog resource deployed from your JFrog Artifactory repository.

## Acceptance criteria
- [ ] Users should be able to view the tags, last update and SHA of an image related to a catalog deployed by a **JFrog** image 

## Requirements
- [ ] Plugin
- [x] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/559 [Doc]
- [x] https://github.com/janus-idp/backstage-plugins/issues/558 [QE]

## Notes
There is a question as to if there should be an OCI Registry frontend plugin which has a number of backend plugins (Quay, ECR, GCR, Nexus, JFrog)

**Additional context**

**Comment by jasperchui** [comment]
Reopen to capture documentation and testing needs.

**Comment by jasperchui** [comment]
Closing EPIC as doc and testing are captured.
