### ISSUE TITLE
🔌 Plugin: OCI Registry (ACR)

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#166]
## Goal
This epic aims to develop a new Backstage plugin in the Janus repo. This plugin should allow Backstage users to view details of an image related to a catalog resource deployed from your Azure Container Registry.

## Acceptance criteria
- [x] Users should be able to view the tags, last update and SHA of an image related to a catalog deployed by an  image in the **Azure Container Registry**

## Requirements
- [x] Plugin
- [x] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] #216 
- [x] https://github.com/janus-idp/backstage-plugins/issues/525 [Docs]
- [x] https://github.com/janus-idp/backstage-plugins/issues/526 [QE]

## Notes
There is a question as to if there should be an OCI Registry frontend plugin which has a number of backend plugins (Quay, ECR, GCR, Nexus, JFrog, ACR)

**Additional context**

**Comment by invincibleJai** [comment]
Closing it as all linked tasks are in close state
