### ISSUE TITLE
Create new custom actions - v1

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#171]
## Goal
This epic aims to enhance the experience for Platform Engineers creating GPTs.  We will provide 3 new custom actions which Platform Engineers to take advantage of:
1. Create a Kubernetes namespace
2. Create a Quay image repository
3. Create a SonarQube project

## Acceptance criteria
- [ ] Users should be able to use a custom action to **create a kubernetes namespace** in their GPT.
- [ ] Users should be able to use a custom action to **create a Quay image repository** in their GPT.
- [ ] Users should be able to use a custom action to **create a SonarQube project** in their GPT.

## Requirements
- [ ] Custom action
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] #175
- [x] #176
- [x] #177 

**Additional context**
Here are some examples of scaffolder-actions in other repos: 
- https://github.com/backstage/backstage/blob/f00e03c38f0de6487af990e0410f4219eb1a8e28/plugins/scaffolder-backend/src/scaffolder/actions/builtin/createBuiltinActions.ts#L40
- https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions
