### ISSUE TITLE
🔌 UI Plugin: Topology, v2

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#191]
## Goal
The goal of this epic is to enhance the Topology plugin.

Features:

**What problem does this solve? Please describe.**
- Users want one-click access to pod logs from the Topology side panel
- Users want the ability to download the pod log
- Users want one-click access to run their application which is running on Kubernetes. This should support OpenShift Routes in addition to the current Ingress support
- Users want the ability to get to their code from the topology view
 
**Use cases**
_Coming after spike review_

**Acceptance criteria**
- View logs tab should be available in the side panel
- 
## Issues in Epic
- [x] #184
- [x] https://github.com/janus-idp/backstage-plugins/issues/469
- [x] https://github.com/janus-idp/backstage-plugins/issues/480
- [x] #250 
- [x] https://github.com/janus-idp/backstage-plugins/issues/377
- [x] https://github.com/janus-idp/backstage-plugins/issues/349
- [x] https://github.com/janus-idp/backstage-plugins/issues/271
- [x] https://github.com/janus-idp/backstage-plugins/issues/395
- [x] https://github.com/janus-idp/backstage-plugins/issues/284
- [x] https://github.com/janus-idp/backstage-plugins/issues/270
- [x] https://github.com/janus-idp/backstage-plugins/issues/490
- [x] https://github.com/janus-idp/backstage-plugins/issues/541
- [x] https://github.com/janus-idp/backstage-plugins/issues/547
- [x] https://github.com/janus-idp/backstage-plugins/issues/548
- [x] https://github.com/janus-idp/backstage-plugins/issues/549

### Topology graph view
<img width="1204" alt="Screenshot 2023-02-03 at 6 35 39 PM" src="https://user-images.githubusercontent.com/12504403/216735353-9e8b405e-4875-4144-82a3-1604fb9b0675.png">

### Topology graph view with side panel showing kubernetes details
<img width="1203" alt="Topology-sidepanel-details" src="https://user-images.githubusercontent.com/12504403/216735417-de5d705b-7062-4205-8c4e-cbce97afbca6.png">

### Topology graph view with side panel showing associated resources
<img width="1200" alt="Topology-sidepanel-resources" src="https://user-images.githubusercontent.com/12504403/216735428-9539674c-e673-4764-b60e-1a89a07203cd.png">

**Comment by invincibleJai** [comment]
@serenamarie125 / @christophe-f have linked some story/spikes for topology V2, will be adding more as we progress based on spikes

Let us know if there are any questions

cc @debsmita1 @divyanshiGupta

**Comment by serenamarie125** [comment]
What do we think about support for the Pipeline decorator @divyanshiGupta @debsmita1 @invincibleJai.  Is that something we could look into as well?

**Comment by invincibleJai** [comment]
> What do we think about support for the Pipeline decorator @divyanshiGupta @debsmita1 @invincibleJai. Is that something we could look into as well?

Yeah it makes sense Serena, have created a ticket and linked it to the epic https://github.com/janus-idp/backstage-plugins/issues/349

PTAL, let us know if any changes needed.

**Comment by invincibleJai** [comment]
> Additionally, the existing Topology plugin shows # pods in the node. Do we have thoughts on the amount of work it will take to bring in the runtime logos as a display option?
> 
> FYI @christophe-f added a couple other thoughts here.

We can definitely incorporate it, then we'll need to store runtime images as we have in console and this also also add a filter in topology toolbar. LMK if it makes sense will create a story for it.

@debsmita1 @divyanshiGupta FYI, lmk if this looks fine.

**Comment by lsharar** [comment]
@jasperchui the documentation work is complete now, can we close this?

**Comment by divyanshiGupta** [comment]
Marked the epic as done and closing this ticket as all linked stories are completed.
