### ISSUE TITLE
[Quay] Increase unit test coverage for Quay plugin

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#443]
**Description:**  Increase unit test coverage for Quay plugin 

Current test coverage:

<img width="1328" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/c5fe7bc1-8056-462a-a0ef-8e333519e21f">

**TODO:**
- [x] Add tests for `QuayRepository`
- [x] Add tests for `QuayTagPage`
- [x] Add tests for `QuayTagDetails`
- [x] Add tests for `Router`
- [x]  Add tests for custom hook `useTags`
- [x]  Add tests for custom hook `useRepository`
- [x]  Add tests for custom hook `useTagDetails`
