### ISSUE TITLE
🔌  Plugin: Multi cluster

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#55]
## Goal
The goal of this epic is to develop a new Backstage plugin in the Janus repo.  The goal is to integrate the Backstage instance with Open Cluster Management's MultiClusterHub and MultiCluster Engine.

## Acceptance Criteria
- All Clusters in the MultiCluterHub should be available in the Backstage catalog.
- Users should be able to see the current cluster status
- When looking at the cluster entity page, users should be able to see the cluster details, including the OpenShift Console link, OCM console link, OCP and Kubernetes version
- When looking at the cluster entity page, users should be able to see the available compute resources 

## Requirements
- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/87
- [x] https://github.com/janus-idp/backstage-plugins/issues/107
- [x] #131 
- [x] #305 

**Additional context**

## Stakeholder sign-off
- [x] QE
- [x] Doc

**Comment by tumido** [comment]
@serenamarie125 do we want some more detail description on what we want to target in here?

In addition to our current state of things in the OCM plugin we want to expand it to also play along nicely with the `kubernetes` plugin. Currently all discovered clusters are loaded into the catalog and we want to use the `kubernetes` native catalog discovery to load and connect to these clusters using user credentials.

We also need to iron out the UI/UX side of things for OCM frontend plugin.

cc @SamoKopecky
