### ISSUE TITLE
🔌  UI Plugin: Application Topology

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#58]
## Goal
The goal of this epic is to develop a  new Backstage UI plugin in the Janus repo.  This UI plugin should provide similar functionality from the Application Topology view in the OpenShift Developer Perspective of the console.  The current Application Topology supports a large set of features.

This plugin will provide an initial set of features, which will continue to be enhanced, based on the success metrics of the initial version of this plugin, including customer feedback.

- The plugin will initially be view only
- The plugin will initially only provide the graph view
- The plugin will visualize information/status in real time
- The visual representations of objects from a shape and hierarchy standpoint will be consistent with what is shown in OpenShift today.
- Nodes will display a pod ring so that users are easily able to see the status of the pods associated with the workloads
- Provide a route decorator
- Side panel showing details of the kubernetes objects
- Resource tab in the side panel showing the associated resources 
- Implement the GH and DevSpaces decorator (stretch)

**What problem does this solve? Please describe.**
- Users want to be able to see the status of the workloads associated with a service in your catalog which is deployed to any kubernetes cluster. 
- Users want one click access to pod logs
- Users want one click access to run their application which is running on kubernetes

**Features**
_Need to look into this further_
- Provide a Topology tab on the entity page which provides the graph view of the application topology ( list view will. come later)
_OR_
- Provide a Topology Card on that visualizes the directly related workloads of the current entity.
- Provide a Topology Page which can be access from the Topology Card, and is able to view the workloads associated with the current entity as well as workloads associated with their relations.
 
**Use cases**
_Coming after spike review_

**Acceptance criteria**
_Coming after spike review_

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/85
- [x] https://github.com/janus-idp/backstage-plugins/issues/89
- [x] https://github.com/janus-idp/backstage-plugins/issues/90
- [x] https://github.com/janus-idp/backstage-plugins/issues/91
- [x] https://github.com/janus-idp/backstage-plugins/issues/105
- [x] https://github.com/janus-idp/backstage-plugins/issues/118
- [x] https://github.com/janus-idp/backstage-plugins/issues/121
- [x] https://github.com/janus-idp/backstage-plugins/issues/122
- [x] https://github.com/janus-idp/backstage-plugins/issues/123
- [x] #109 (once initial PR has been merged)
- [x] https://github.com/janus-idp/backstage-plugins/issues/70
- [x] https://github.com/janus-idp/backstage-plugins/issues/72
- [x] https://github.com/janus-idp/backstage-plugins/issues/183
- [x] https://github.com/janus-idp/backstage-plugins/issues/229
- [x] #132 
- [x] #306 

## Stakeholder sign-off
- [x] QE
- [x] Doc

### Topology graph view
<img width="1204" alt="Screenshot 2023-02-03 at 6 35 39 PM" src="https://user-images.githubusercontent.com/12504403/216735353-9e8b405e-4875-4144-82a3-1604fb9b0675.png">

### Topology graph view with side panel showing kubernetes details
<img width="1203" alt="Topology-sidepanel-details" src="https://user-images.githubusercontent.com/12504403/216735417-de5d705b-7062-4205-8c4e-cbce97afbca6.png">

### Topology graph view with side panel showing associated resources
<img width="1200" alt="Topology-sidepanel-resources" src="https://user-images.githubusercontent.com/12504403/216735428-9539674c-e673-4764-b60e-1a89a07203cd.png">

**Comment by taras** [comment]
It might be worth looking at the [Catalog Graph plugin](https://roadie.io/backstage/plugins/catalog-graph/)

**Comment by serenamarie125** [comment]
@taras thanks for the reference.  I've started to more clearly articulate the goals of this plugin, hope this helps.

**Comment by taras** [comment]
Thank you. They're similar but your mockups are much prettier. The Graph plugin hasn't gotten a lot of love since it was created. What you folks are planning is exciting!

**Comment by serenamarie125** [comment]
FYI @invincibleJai note that I added #250 as a stretch

**Comment by rtaniwa** [comment]
@josephca @rnapoles-rh can one of you sign off for QE. 
@hmanwani-rh @rkratky can one of you sign off for doc?
