### ISSUE TITLE
🔌  Plugin: Improve upstream GitHub UI Plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#61]
## Goal
Improve upstream GitHub UI Plugin

## What problem does this solve? Please describe.
Application developers want to be able to view GitHub issues associated with their entity.

## Use cases
As an application developer using the Backstage portal, I should be able to view GitHub issues for my entity in Backstage.

## Acceptance criteria
- [x] Evaluate the plugin, using this [BS Plugin Evaluation Templates](https://docs.google.com/document/d/10bltPXv9G-2Ev_JmtZyk0H5FJeptZCmYhS6M95CLcHU/edit)
- [x] Review above evaluation and determine next steps
- [x] Identify any upstream issues that need to be addressed and fix them

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/92
- [x] https://github.com/backstage/backstage/issues/15848

**Comment by invincibleJai** [comment]
There is a plugin for github issues https://github.com/backstage/backstage/tree/master/plugins/github-issues 

shared by @PatAKnight

**Comment by divyanshiGupta** [comment]
Captured results/outcome here - https://docs.google.com/document/d/10J6_FUdmItT-Ko8K7-55RCR2EwbM4Dc_3s921IWLE8o/edit?usp=sharing

**Comment by divyanshiGupta** [comment]
Plugin evaluation doc - https://docs.google.com/document/d/1X8zAeMj5MLl0UMA2VQ1yV_hSre5g108-W1PUaD5DkPc/edit?usp=sharing

**Comment by rtaniwa** [comment]
We did an offline review of the spike, and with the PR getting merged in the upstream we feel the plugin is now complete for our requirements. It is also included in the showcase app already.

I am closing this issue off as complete.
