### ISSUE TITLE
Create a showcase application and run it

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-plugins#69]
**Goal**
Create a  Backstage showcase application and repository with all the supported plugins available. 

The showcase application should be based on [backstage-build](https://github.com/janus-idp/redhat-backstage-build). 
There should be instructions available on deploying the showcase using [ Backstage Helm](https://github.com/janus-idp/helm-backstage).  An instance of the showcase should be deployed and available on OperateFirst.

**What problem does this solve? Please describe.**
It provides a showcase environment for Janus supported plugins and allows the dev team to start from a baseline 

** List of Plugins **
- Kubernetes Plugin 
- ...

**Acceptance criteria**
- [ ] Application is created based on backstage-build and available as a github repo. 
- [ ] Instructions are available for deploying with Helm Chart
- [ ] An instance is running on OperateFirst and automatically updated with updates.
- [ ] Work with @christophe-f to use the Janus branding he's used in the Assemble demos.

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-showcase/issues/5
- [x] https://github.com/janus-idp/backstage-showcase/issues/4
- [x] https://github.com/janus-idp/backstage-showcase/issues/6
- [x] https://github.com/janus-idp/backstage-showcase/issues/7
- [x] https://github.com/janus-idp/backstage-showcase/issues/8
- [x] https://github.com/janus-idp/backstage-showcase/issues/9
- [x] https://github.com/janus-idp/backstage-showcase/issues/10
- [x] https://github.com/janus-idp/backstage-showcase/issues/23
- [x] https://github.com/janus-idp/backstage-showcase/issues/24
- [x] https://github.com/janus-idp/backstage-showcase/issues/25

**Comment by tumido** [comment]
I've created a namespace for this in Operate First:

https://github.com/operate-first/apps/blob/master/cluster-scope/base/core/namespaces/janus-idp/namespace.yaml

If we want to be more transparent, we can make it public-view for the community (we do that with other namespaces so people can peek behind the scenes).

Additionally all people who should have admin access to the namespace can be added here:
https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml

We can also install the helm chart through ArgoCD, so we have 0 manual maintenance with this in the future.

**Comment by tumido** [comment]
> @gorkem can you confirm this is the list of plugins we currently want in the app:
> 
> * [Keycloak](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/keycloak-backend?rgh-link-date=2023-01-13T21%3A03%3A25Z)
> * [Multi-cluster](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/ocm-backend?rgh-link-date=2023-01-13T21%3A03%3A25Z)
> * [Kubernetes](https://backstage.io/docs/features/kubernetes/overview)
> * [Tekton](https://github.com/jquad-group/backstage-jquad#readme)
> * [ArgoCD](https://roadie.io/backstage/plugins/argo-cd/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=argo-cd)
> * [GitHub Issues](https://github.com/backstage/backstage/tree/master/plugins/github-issues?rgh-link-date=2023-01-13T21%3A03%3A25Z)

Piggybacking on the list above for documentation/visibility purposes.

Operate first currently features and can provide access to:
- ACM
- ArgoCD
- Tekton

We would need to deploy our own: 
- Keycloak

**Comment by gorkem** [comment]
@christophe-f feels like we can close this one.

**Comment by christophe-f** [comment]
Yes
