### ISSUE TITLE
[RBAC Plugin] Support creation of Role

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#844]
What do you want to improve?
Support creation of Role (Check with @parvathyvr on the flow)

Screenshots:

<img width="1038" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/453fddcf-c3db-4e96-92e8-559063cfea23">

**Acceptance criteria:**

- [x] Show CTA button on the list roles page
- [x] Click on Create button should take the user to a new create page with breadcrumbs
- [x] Show the stepper component with each step as per the design and on final submission it should create the required roles and policy

**Sub Tasks:**

- [x] [[RBAC Plugin] Add create role form](https://github.com/janus-idp/backstage-plugins/issues/941) 
- [x] [[RBAC plugin] Add support for adding permissions to the role](https://github.com/janus-idp/backstage-plugins/issues/975)
- [x] [[RBAC Plugin] Add create role CTA on roles list page](https://github.com/janus-idp/backstage-plugins/issues/942)

**Additional info:** https://docs.google.com/document/d/1XLUN-2yE7BDRb5PQp5_6sv6f-qR4wBNOSprCuYQygII/edit

**Comment by divyanshiGupta** [comment]
Closing this as all linked sub-tasks are completed.
