### ISSUE TITLE
UI for User and RBAC management

### ISSUE THREAD

**Issue by rtaniwa** [janus-idp/backstage-plugins#849]
Requirements

- As a RHDH admin, I need to be able to select more than one permission for the object so that I can apply the rule to all of them at once.
- As a RHDH admin, I need to see a list of all entitlements for a role to know what entitlements are applied.
- As a RHDH admin, I need to be able to edit and delete an entitlement on a role to adjust the access given to that role.
- As a RHDH admin, I want to change the name of the role I have created.
- As a RHDH admin, I must set a name for a new role before I can save it.

## Requirements
- [ ] Feature
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/840
- [x] https://github.com/janus-idp/backstage-plugins/issues/841
- [x] https://github.com/janus-idp/backstage-plugins/issues/842
- [x] https://github.com/janus-idp/backstage-plugins/issues/843
- [x] https://github.com/janus-idp/backstage-plugins/issues/844 
- [x] https://github.com/janus-idp/backstage-plugins/issues/853
- [x] https://github.com/janus-idp/backstage-plugins/issues/854
- [x] https://github.com/janus-idp/backstage-plugins/issues/1035

**Comment by invincibleJai** [comment]
Moved to milestone 5

cc @rtaniwa

**Comment by invincibleJai** [comment]
Closing it as all linked tickets are closed
